<a href="https://colab.research.google.com/github/Fedo682/FlightpathdelaysProject/blob/main/notebooks/newfile.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Flight Delays Data Science Project

## We will start loading the data from the datasets

importing essential python libaries

In [3]:
import numpy as np
import pandas as pd

In [4]:
airport_raw = pd.read_csv("../data/Raw/airports.csv")
airport_raw.head()

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,icao_code,iata_code,gps_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total RF Heliport,40.070985,-74.933689,11.0,NaN,US,US-PA,Bensalem,no,NaN,NaN,K00A,00A,https://www.penndot.pa.gov/TravelInPA/airports...,NaN,NaN
1,323361,00AA,small_airport,Aero B Ranch Airport,38.704022,-101.473911,3435.0,NaN,US,US-KS,Leoti,no,NaN,NaN,00AA,00AA,NaN,NaN,NaN
2,6524,00AK,small_airport,Lowell Field,59.947733,-151.692524,450.0,NaN,US,US-AK,Anchor Point,no,NaN,NaN,00AK,00AK,NaN,NaN,NaN
3,6525,00AL,small_airport,Epps Airpark,34.864799,-86.770302,820.0,NaN,US,US-AL,Harvest,no,NaN,NaN,00AL,00AL,NaN,NaN,NaN
4,506791,00AN,small_airport,Katmai Lodge Airport,59.093287,-156.456699,80.0,NaN,US,US-AK,King Salmon,no,NaN,NaN,00AN,00AN,NaN,NaN,NaN

In [9]:
delays_raw = pd.read_excel("../data/Raw/RP4_APT_ATFM_ARR_2026_Jan_Feb.xlsx", sheet_name="APT_ATFM_APT", header=4)
delays_raw.head()

,State,Apt. name,ICAO,Apt. ATFM dly [min./arr.],FLTS [ARR],Airport ATFM arr. delay [total]
0,Belgium,Brussels (EBBR),EBBR,0.255875,13999.0,3582.0
1,Germany,Berlin - Brandenburg (EDDB),EDDB,1.359219,12349.0,16785.0
2,Germany,Dresden (EDDC),EDDC,0.000000,643.0,0.0
3,Germany,Erfurt (EDDE),EDDE,0.000000,143.0,0.0
4,Germany,Frankfurt (EDDF),EDDF,1.050781,30287.0,31825.0

* now we have read the Dataframes next we will conduct cleaning and merging the datasets